version: '2'
services:
  proxy:
    build: proxy
    ports:
      - 80:80
  server:
    build: server
    volumes:
      - ./server/database:/usr/src/app/database

networks:
  default:
    external:
      name: help-chat
