version: '2'
services:
  proxy:
    build: proxy
    ports:
      - 80:80
  server:
    build: server
    ports:
      - '3000'
      - '3001'

networks:
  default:
    external:
      name: help-chat
